apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: c10
  policyController:
    enabled: true
  git:
    syncRepo: https://github.com/digitalemil/anthos-config-managment.git
    syncBranch: 1.0.0
    secretType: none
    policyDir: thegym
  configConnector:
    enabled: true
---
